name: CI

on:
  push:
    branches: [develop]

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
          - name: "Check out git repository"
            uses: actions/checkout@v4
    
          - name: Use Node.js v18+
            uses: actions/setup-node@v4
            with:
              node-version: 18.x

          - name: "Linting"
            run: npm run lint
            
          - name: "Test"
            run: npm run test

          - name: "Build"
            run: npm run build